"""empty message

Revision ID: 45216fa4090b
Revises: 617aa4dfe9a8
Create Date: 2023-06-13 18:51:18.128858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45216fa4090b'
down_revision = '617aa4dfe9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_energy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lightsNumber', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_energy', schema=None) as batch_op:
        batch_op.drop_column('lightsNumber')

    # ### end Alembic commands ###
