"""empty message

Revision ID: 617aa4dfe9a8
Revises: dd3b5e97a2db
Create Date: 2023-06-13 14:35:36.981096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617aa4dfe9a8'
down_revision = 'dd3b5e97a2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_energy',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dishwasher', sa.String(length=75), nullable=False),
    sa.Column('dishwasherLoads', sa.Integer(), nullable=False),
    sa.Column('washer', sa.String(length=75), nullable=False),
    sa.Column('washerLoads', sa.Integer(), nullable=False),
    sa.Column('dryer', sa.String(length=75), nullable=False),
    sa.Column('dryerLoads', sa.Integer(), nullable=False),
    sa.Column('lights', sa.String(length=75), nullable=False),
    sa.Column('lightsTime', sa.Integer(), nullable=False),
    sa.Column('hvac', sa.String(length=75), nullable=False),
    sa.Column('hvacTime', sa.Integer(), nullable=False),
    sa.Column('hvacTemp', sa.Integer(), nullable=False),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transportation', schema=None) as batch_op:
        batch_op.alter_column('carpool',
               existing_type=sa.VARCHAR(length=75),
               type_=sa.String(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transportation', schema=None) as batch_op:
        batch_op.alter_column('carpool',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=75),
               existing_nullable=False)

    op.drop_table('home_energy')
    # ### end Alembic commands ###
