"""empty message

Revision ID: dd3b5e97a2db
Revises: 67982ab27d6a
Create Date: 2023-05-12 00:10:11.793092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3b5e97a2db'
down_revision = '67982ab27d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transportation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(), nullable=False))
        batch_op.drop_constraint('transportation_user_token_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['token'], ['token'])
        batch_op.drop_column('user_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transportation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transportation_user_token_fkey', 'user', ['user_token'], ['token'])
        batch_op.drop_column('token')

    # ### end Alembic commands ###
